# Generated by Django 3.2.5 on 2022-04-16 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Bird Name')),
                ('description', models.TextField(max_length=120, verbose_name='Bird Description')),
                ('point_value', models.BigIntegerField(blank=True)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='BirdFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Bird Name')),
                ('picture', models.ImageField(upload_to='')),
                ('birdfound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='starting.bird')),
                ('finders', models.ManyToManyField(blank=True, to='starting.User')),
            ],
        ),
    ]
