# Generated by Django 3.2.5 on 2022-04-17 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birdfound',
            name='finders',
        ),
        migrations.RemoveField(
            model_name='birdfound',
            name='name',
        ),
    ]
