# Generated by Django 3.2.5 on 2022-04-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starting', '0002_auto_20220416_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birds_found',
            field=models.ManyToManyField(blank=True, to='starting.Bird'),
        ),
    ]
